CARLA_HOSTS = ["localhost", 2000]
CARLA_TIMEOUT = 20.0
CARLA_MAP = "Town02"

VEHICLE = "model3"

LIDAR_TOPIC = "/carla_lidar"
LIDAR_FRAME = "carla_lidar"
LIDAR_CHANNEL = 64
LIDAR_RANGE = 100
LIDAR_UPPER_FOV = 20.0
LIDAR_LOWER_FOV = -20.0
LIDAR_FREQUENCY = 20.0
LIDAR_POINT_PER_SENCOD = 320000
LIDAR_NOISE_STDDEV = 0.0

IMAGE_TOPIC = "/carla_image"
IMAGE_WIDTH  = 640
IMAGE_HEIGHT = 480
IMAGE_FOV    = 90

IMU_TOPIC = "/carla_imu"
IMU_FRAME = "base_link"